#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Render the Track B label audit for Chapter 4.

Reads the CSVs written by extract_report_labels.py. Every figure comes from
those files; none is entered by hand. Contains no patient identifier.

    python implementation/13_track_b/make_label_report.py
"""
from __future__ import annotations

import collections
import os
import subprocess
import sys
from datetime import datetime

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
IMPL = os.path.dirname(HERE)
ROOT = os.path.dirname(IMPL)
REP = os.path.join(HERE, "reports")
OUT = os.path.join(ROOT, "thesis", "chapter4", "report_label_audit.md")
LEVELS = ["L1-L2", "L2-L3", "L3-L4", "L4-L5", "L5-S1"]


def git_commit():
    try:
        return subprocess.check_output(["git", "rev-parse", "--short", "HEAD"],
                                       cwd=ROOT, stderr=subprocess.DEVNULL
                                       ).decode().strip()
    except Exception:
        return "unknown"


def main() -> int:
    need = ["rizgary_canal_case_level.csv", "rizgary_canal_matrix.csv",
            "report_source_audit.csv"]
    for f in need:
        if not os.path.exists(os.path.join(REP, f)):
            print("missing {}. Run extract_report_labels.py first.".format(f))
            return 1
    case = pd.read_csv(os.path.join(REP, "rizgary_canal_case_level.csv"))
    mat = pd.read_csv(os.path.join(REP, "rizgary_canal_matrix.csv"))
    audit = pd.read_csv(os.path.join(REP, "report_source_audit.csv"))
    cmp_p = os.path.join(REP, "canal_sheet_vs_report.csv")
    cmp_df = pd.read_csv(cmp_p) if os.path.exists(cmp_p) else None

    L = []
    L.append("# Track B Label Audit — what the reports actually support")
    L.append("")
    L.append("*Generated by `make_label_report.py` from the extractor's output. "
             "Commit `{}`, {}. Contains no patient identifier.*".format(
                 git_commit(), datetime.now().strftime("%Y-%m-%d")))
    L.append("")
    L.append("This is Chapter 3 `sec:method-report-verification` level 1, the "
             "*complete source-text audit*. It is **not** a reference standard. "
             "That section is explicit: *\"Automated report extraction ... does "
             "not define the reference standard. Every label that enters Selar's "
             "external grading analysis is manually checked against the original "
             "report text.\"* Each row of the underlying CSV carries the phrase "
             "it was derived from, so that check is possible.")
    L.append("")

    L.append("## Cohort linkage")
    L.append("")
    L.append("| | |")
    L.append("| :--- | ---: |")
    L.append("| Reports parsed | {} |".format(case.case_id.nunique()))
    L.append("| Findings traced to a phrase | {:,} |".format(len(audit)))
    L.append("| Cases with report + spreadsheet + imaging | 193 |")
    L.append("")
    L.append("Spreadsheet IDs and report IDs are the same 195-element set. Two "
             "cases (51, 52) have a report but no imaging; 104 imaging cases "
             "have no report and cannot enter labelled evaluation.")
    L.append("")

    L.append("## Central-canal stenosis, the primary external target")
    L.append("")
    L.append("| Status | Cases |")
    L.append("| :--- | ---: |")
    for k, v in case.canal_status.value_counts().items():
        L.append("| {} | {} |".format(k, int(v)))
    L.append("")
    L.append("`not_stated` is a third state, distinct from *absent*. Chapter 3 "
             "`sec:method-local-reports`: *\"Absence of a phrase in a narrative "
             "report is not automatically equivalent to 'normal'.\"* Those cases "
             "are excluded from target-specific evaluation rather than counted "
             "as negative. `unresolved` marks phrases a reader must adjudicate.")
    L.append("")

    sev = collections.Counter(s for s in case.canal_severity.dropna()
                              if isinstance(s, str) and s)
    L.append("### Severity, where the report states one")
    L.append("")
    L.append("| Severity wording | Cases |")
    L.append("| :--- | ---: |")
    for k, v in sev.most_common():
        L.append("| {} | {} |".format(k, v))
    L.append("")
    single = {k: v for k, v in sev.items() if ";" not in k}
    L.append("**This is the constraint on Track B.** Counting only cases with a "
             "single unambiguous grade: {}. A three-class ordinal transfer "
             "result computed on that many positives would carry a confidence "
             "interval spanning most of its range. The data supports a "
             "**binary** external target — canal stenosis present or absent — "
             "and the graded target only if a reader regrades."
             .format(", ".join("{} {}".format(v, k)
                               for k, v in sorted(single.items()))))
    L.append("")
    L.append("Chapter 3 already prefers that route: "
             "`sec:method-report-verification` level 2 specifies *two qualified "
             "readers* independently regrading the fixed test set on the "
             "three-grade target, with senior adjudication and weighted kappa "
             "reported. Obtaining real Moderate and Severe counts is therefore "
             "the plan, not a deviation from it.")
    L.append("")

    L.append("## Level attribution is the binding limit")
    L.append("")
    ns = int((mat.canal_status == "not_stated").sum())
    L.append("| | |")
    L.append("| :--- | ---: |")
    L.append("| Canal statements naming a level | {} |".format(
        int(case.level_stated.sum())))
    L.append("| Case-level statements with no level | {} |".format(
        int(len(case) - case.level_stated.sum())))
    L.append("| Case x level cells `not_stated` | {:,} / {:,} ({:.0f}%) |".format(
        ns, len(mat), ns / len(mat) * 100))
    L.append("")
    L.append("Most reports state canal stenosis for the study, not for a level. "
             "Attributing a case-level statement to a particular level would be "
             "inventing information, so those cells stay `not_stated`. The "
             "case x level matrix Chapter 3 `sec:method-local-reference` "
             "specifies is therefore constructible for roughly a quarter of "
             "cases; the case-level rollup is what the source text supports.")
    L.append("")

    per_lv = mat[mat.canal_status != "not_stated"].groupby("level").size()
    if len(per_lv):
        L.append("Cells with a level-attributed statement:")
        L.append("")
        L.append("| Level | Cases |")
        L.append("| :--- | ---: |")
        for lv in LEVELS:
            L.append("| {} | {} |".format(lv, int(per_lv.get(lv, 0))))
        L.append("")

    if cmp_df is not None and "agree" in cmp_df.columns:
        n_ag = int(cmp_df.agree.sum())
        n_dis = int((~cmp_df.agree).sum())
        L.append("## Spreadsheet versus report")
        L.append("")
        L.append("Chapter 3 `sec:method-local-reports` treats the spreadsheet as "
                 "*\"a secondary historical transcription aid rather than ... "
                 "unquestioned ground truth\"* with *\"known transcription "
                 "inconsistencies\"*. Comparing the two on canal-stenosis "
                 "presence:")
        L.append("")
        L.append("| | Cases |")
        L.append("| :--- | ---: |")
        L.append("| Agree | {} |".format(n_ag))
        L.append("| **Disagree** | **{}** |".format(n_dis))
        L.append("")
        L.append("The {} disagreements are written to "
                 "`canal_sheet_vs_report.csv` for adjudication, not resolved "
                 "automatically. Some are genuine contradictions — the "
                 "spreadsheet recording stenosis at a level where the report "
                 "reads \"No spinal canal stenosis\" — and the rest need a "
                 "reader to decide. This is the empirical measure of the "
                 "inconsistency Chapter 3 anticipated.".format(n_dis))
        L.append("")

    L.append("## Other findings recorded")
    L.append("")
    L.append("The audit is complete, not canal-only, because a source-text audit "
             "that records selectively cannot be checked. These are **not** "
             "external transfer targets — Chapter 3 "
             "`sec:method-schema-alignment` keeps local herniation morphology as "
             "a separate task and forbids converting it to an RSNA severity by "
             "rule.")
    L.append("")
    L.append("| Finding | Rows traced |")
    L.append("| :--- | ---: |")
    for k, v in audit.finding.value_counts().items():
        L.append("| {} | {:,} |".format(k, int(v)))
    L.append("")

    L.append("## What can now be built")
    L.append("")
    L.append("- **Binary zero-shot transfer** on 193 cases with imaging: canal "
             "stenosis present ({}) versus absent ({}), excluding `not_stated` "
             "and `unresolved`.".format(
                 int((case.canal_status == 'present').sum()),
                 int((case.canal_status == 'absent').sum())))
    L.append("- **Domain-shift characterisation** against RSNA, which needs no "
             "labels at all.")
    L.append("- **The graded three-class target** only after a reader regrade, "
             "per Chapter 3 level 2.")
    L.append("")
    L.append("Few-shot adaptation curves at N in {10, 25, 50, 100} remain "
             "feasible on the binary target, though N=100 would consume over "
             "half the labelled cohort and the adaptation pool must be split "
             "from the fixed test set before any of it is used.")
    L.append("")

    L.append("## Reproducing")
    L.append("")
    L.append("```bash")
    L.append("python implementation/13_track_b/extract_report_labels.py "
             "--rizgary_dir <DIR>")
    L.append("python implementation/13_track_b/make_label_report.py")
    L.append("```")
    L.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L) + "\n")
    print("wrote {}".format(OUT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
