#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Render the Rizgary cohort reconciliation for Chapter 4.

Chapter 3 sec:method-reconciliation: "Before any local model evaluation, a
case-flow table will reconcile the raw archive, reports and analysable imaging."
This renders the imaging half of that table from survey_rizgary.py's output, and
states plainly which of Chapter 3's requirements the available data cannot yet
meet.

Contains no patient identifier: the survey reduces names and IDs to salted
hashes used only to count, dates to years, ages to decades.

    python implementation/13_track_b/make_cohort_report.py
"""
from __future__ import annotations

import collections
import os
import subprocess
import sys
from datetime import datetime

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
IMPL = os.path.dirname(HERE)
ROOT = os.path.dirname(IMPL)
FLOW = os.path.join(HERE, "reports", "rizgary_case_flow.csv")
OUT = os.path.join(ROOT, "thesis", "chapter4", "rizgary_cohort_reconciliation.md")


def git_commit():
    try:
        return subprocess.check_output(["git", "rev-parse", "--short", "HEAD"],
                                       cwd=ROOT, stderr=subprocess.DEVNULL
                                       ).decode().strip()
    except Exception:
        return "unknown"


def main() -> int:
    if not os.path.exists(FLOW):
        print("run survey_rizgary.py first")
        return 1
    df = pd.read_csv(FLOW)

    names = collections.Counter(h for s in df.name_hash.dropna()
                                for h in str(s).split(";") if h)
    pids = collections.Counter(h for s in df.pid_hash.dropna()
                               for h in str(s).split(";") if h)
    rep = collections.Counter(names.values())
    repeats = sum((k - 1) * v for k, v in rep.items() if k > 1)

    folder_of = {}
    for r in df.itertuples(index=False):
        for h in str(r.name_hash).split(";"):
            if h:
                folder_of.setdefault(h, set()).add(r.folder_label)
    cross = {h: v for h, v in folder_of.items() if len(v) > 1}

    all3 = int(((df.has_sag_t1 + df.has_sag_t2 + df.has_ax_t2) == 3).sum())

    L = []
    L.append("# Rizgary Cohort Reconciliation (Track B, step 0)")
    L.append("")
    L.append("*Generated by `make_cohort_report.py` from the survey output. "
             "Commit `{}`, {}. Contains no patient identifier.*"
             .format(git_commit(), datetime.now().strftime("%Y-%m-%d")))
    L.append("")
    L.append("Chapter 3 `sec:method-reconciliation` requires this table before "
             "any local model evaluation. It reconciles what the archive "
             "actually contains against what the methodology assumes.")
    L.append("")

    L.append("## The imaging is sound")
    L.append("")
    L.append("| | |")
    L.append("| :--- | ---: |")
    L.append("| Case directories | {} |".format(len(df)))
    L.append("| Readable DICOM | {} |".format(int((df.n_dicom > 0).sum())))
    L.append("| DICOM instances | {:,} |".format(int(df.n_dicom.sum())))
    L.append("| Series | {:,} |".format(int(df.n_series.sum())))
    L.append("| Series carrying IOP/IPP/PixelSpacing | {:,} ({:.1f}%) |".format(
        int(df.n_series_with_geometry.sum()),
        df.n_series_with_geometry.sum() / max(df.n_series.sum(), 1) * 100))
    L.append("")
    L.append("| Sequence | Cases |")
    L.append("| :--- | ---: |")
    for c, n in [("has_sag_t1", "Sagittal T1"), ("has_sag_t2", "Sagittal T2/STIR"),
                 ("has_ax_t2", "Axial T2")]:
        L.append("| {} | {} / {} |".format(n, int(df[c].sum()), len(df)))
    L.append("| **All three** | **{} / {}** |".format(all3, len(df)))
    L.append("")
    L.append("Six cases lack a sequence and are listed at the end. Scanner "
             "distribution is near-uniform ({}), all studies from one year, so "
             "acquisition variation within the local cohort is small — the "
             "domain shift Track B measures is against RSNA, not within "
             "Rizgary.".format(
                 ", ".join("{} x{}".format(k, v) for k, v in
                           collections.Counter(
                               x for s in df.scanners.dropna()
                               for x in str(s).split(";") if x).most_common(3))))
    L.append("")

    L.append("## Four findings that block Track B as specified")
    L.append("")
    L.append("### 1. The narrative reports are absent")
    L.append("")
    L.append("No `.doc`, `.pdf`, `.txt` or `.rtf` file exists anywhere under the "
             "cohort directory. Chapter 3 `sec:method-local-reports` makes them "
             "the primary source: *\"The methodology reconstructs the local "
             "reference matrix from source reports and uses the spreadsheet only "
             "for cross-checking.\"* Only the secondary aid is present.")
    L.append("")
    L.append("### 2. The spreadsheet cannot be joined to the imaging")
    L.append("")
    L.append("`research LSS 1.xlsx` holds 195 rows and 18 columns — age, gender "
             "and free-text findings — and **no case or patient identifier**. "
             "There is therefore no key linking a row to any of the {} imaging "
             "cases. Row order might encode one, but assuming that would be "
             "manufacturing a linkage rather than reconciling one.".format(len(df)))
    L.append("")
    L.append("Three counts disagree: **195** spreadsheet rows, **{}** imaging "
             "cases, and Chapter 3's stated **299 reports / 294 cases**."
             .format(len(df)))
    L.append("")
    L.append("### 3. The labels are neither level-resolved nor graded")
    L.append("")
    L.append("The `spinal canal stenosis` column — the target Chapter 3 names as "
             "primary for external transfer — is free text with 37 distinct "
             "values: `L4-5`, `L3-4,L4-5 mild`, `mild at L4-5`, `none` (127 of "
             "195). Most entries give a level list with no severity, so they "
             "cannot be mapped onto the Normal/Mild - Moderate - Severe target. "
             "Chapter 3 anticipated exactly this: *\"it does not constitute a "
             "complete level-resolved RSNA-style matrix and has known "
             "transcription inconsistencies.\"*")
    L.append("")
    L.append("### 4. The folder labels are not a per-case classification")
    L.append("")
    L.append("**{} patient-name hashes appear under more than one morphology "
             "folder**, one of them under bulge, protrusion *and* extrusion. "
             "Either a patient was filed once per finding — in which case the "
             "folders index findings, not cases, and treating them as a 4-class "
             "target would be wrong — or the names collide. Both readings must "
             "be resolved before the folders are used as labels."
             .format(len(cross)))
    L.append("")

    L.append("## A de-identification defect")
    L.append("")
    L.append("`00_deidentify/deidentify_dicom.py` derives each pseudonym by "
             "hashing `PatientID`. Across the cohort:")
    L.append("")
    L.append("| | |")
    L.append("| :--- | ---: |")
    L.append("| Cases | {} |".format(len(df)))
    L.append("| Distinct `PatientID` values | **{}** |".format(len(pids)))
    L.append("| `PatientID` values shared by >1 case | {} |".format(
        sum(1 for v in pids.values() if v > 1)))
    L.append("| Distinct `PatientName` values | {} |".format(len(names)))
    L.append("")
    L.append("Hashing `PatientID` would map roughly {:.0f} cases onto every "
             "pseudonym. That is not merely a privacy question: Chapter 3 "
             "`sec:method-patient-split` rests on patient-level partitioning, "
             "and a key that merges distinct patients — or splits one patient "
             "across pseudonyms — corrupts the leakage control everything else "
             "depends on. A per-case key derived from the study, not the "
             "patient record, is required."
             .format(len(df) / max(len(pids), 1)))
    L.append("")

    L.append("## Repeat imaging")
    L.append("")
    L.append("| Cases sharing one name hash | Distinct names | Cases |")
    L.append("| ---: | ---: | ---: |")
    for k in sorted(rep):
        L.append("| {} | {} | {} |".format(k, rep[k], k * rep[k]))
    L.append("")
    L.append("**{} cases are potential repeat examinations** of a patient "
             "already in the cohort. Chapter 3 `sec:method-reconciliation`: "
             "*\"Repeat examinations from one patient, if identified, remain in "
             "the same partition to preserve patient independence.\"* Splitting "
             "Track B by case rather than by patient would leak up to {} cases "
             "across the boundary.".format(repeats, repeats))
    L.append("")

    L.append("## What can proceed, and what cannot")
    L.append("")
    L.append("**Can proceed now.** The imaging cohort is usable: {} of {} cases "
             "carry all three required sequences with valid DICOM geometry. "
             "Geometry parsing, ROI construction and domain-shift "
             "characterisation against RSNA (intensity, spacing, field of view) "
             "need no labels at all.".format(all3, len(df)))
    L.append("")
    L.append("**Cannot proceed.** Zero-shot evaluation and few-shot adaptation "
             "both require the local reference standard, and it cannot be "
             "constructed from what is on disk. Reporting a Track B transfer "
             "number without it would mean inventing labels.")
    L.append("")
    L.append("**Three ways forward**, in the order Chapter 3 would prefer:")
    L.append("")
    L.append("1. **Obtain the 299 reports** and the case identifiers that link "
             "them to imaging. This is the only route that delivers Track B as "
             "written.")
    L.append("2. **Have a radiologist re-read a subset**, producing the "
             "case-level central-canal matrix directly. Chapter 3 already "
             "contemplates this: foraminal and subarticular targets are to be "
             "excluded *\"unless new expert annotation is created\"*.")
    L.append("3. **Rescope Track B to the local morphology task** the folders "
             "support. Chapter 3 sanctions this as *\"a separate local "
             "morphology task\"*, but it is no longer zero-shot transfer of the "
             "RSNA stenosis model, and the chapter would need to say so.")
    L.append("")
    L.append("Option 3 additionally depends on resolving finding 4 above.")
    L.append("")

    bad = df[(df.has_sag_t1 + df.has_sag_t2 + df.has_ax_t2) < 3]
    if len(bad):
        L.append("## Cases missing a required sequence")
        L.append("")
        L.append("| Folder | Case | Missing |")
        L.append("| :--- | :--- | :--- |")
        for r in bad.itertuples(index=False):
            miss = [n for n, c in [("sagittal T1", r.has_sag_t1),
                                   ("sagittal T2", r.has_sag_t2),
                                   ("axial T2", r.has_ax_t2)] if not c]
            L.append("| {} | `{}` | {} |".format(
                r.folder_label, r.case, ", ".join(miss)))
        L.append("")

    L.append("## Reproducing")
    L.append("")
    L.append("```bash")
    L.append("python implementation/13_track_b/survey_rizgary.py --rizgary_dir <DIR>")
    L.append("python implementation/13_track_b/make_cohort_report.py")
    L.append("```")
    L.append("")
    L.append("The survey unpacks the archives into `data/rizgary_unpacked/`, "
             "which is gitignored. The unpacked DICOMs still carry unredacted "
             "identifiers and must not leave that directory until "
             "de-identification is fixed.")
    L.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L) + "\n")
    print("wrote {}".format(OUT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
