#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Render the E0 baseline for Chapter 4 from the PIPELINE's result files.

Reads data/derived/E0_real_seed*_test.json -- the output of amog_train.py, the
engine the whole ladder runs on. An earlier version of this document was built
from a standalone E0 harness in 06_baselines; that harness used a different
split and the ROI geometry the ablation later rejected, so its numbers are not
comparable to the ladder's and are superseded.

    python implementation/99_audit/make_e0_report.py
"""
from __future__ import annotations

import glob
import json
import os
import subprocess
import sys
from datetime import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
IMPL = os.path.dirname(HERE)
ROOT = os.path.dirname(IMPL)
DERIVED = os.path.join(ROOT, "data", "derived")
OUT = os.path.join(ROOT, "thesis", "chapter4", "e0_baseline.md")
GRADES = ["Normal/Mild", "Moderate", "Severe"]


def git_commit():
    try:
        return subprocess.check_output(["git", "rev-parse", "--short", "HEAD"],
                                       cwd=ROOT, stderr=subprocess.DEVNULL
                                       ).decode().strip()
    except Exception:
        return "unknown"


def load(pattern):
    out = []
    for p in sorted(glob.glob(os.path.join(DERIVED, pattern))):
        with open(p, encoding="utf-8") as fh:
            out.append((os.path.basename(p), json.load(fh)))
    return out


def cache_meta():
    p = os.path.join(ROOT, "data", "cache", "rsna_roi_v2_meta.json")
    if os.path.exists(p):
        with open(p, encoding="utf-8") as fh:
            return json.load(fh)
    return {}


def split_meta():
    p = os.path.join(IMPL, "splits", "rsna_patient_split_meta.json")
    if os.path.exists(p):
        with open(p, encoding="utf-8") as fh:
            return json.load(fh)
    return {}


def main() -> int:
    real = [(n, d) for n, d in load("E0_real_seed*_test.json")
            if "LABELSHUF" not in n]
    ctrl = [(n, d) for n, d in load("E0_real_seed*_test.json")
            if "LABELSHUF" in n]
    ctrl += load("E0_LABELSHUF_real_seed*_test.json")

    if not real:
        print("no real E0 result found in {}".format(DERIVED))
        print("run: python implementation/amog_train.py --stage E0 --mode real")
        return 1

    _n, r = real[0]
    cm = cache_meta()
    sm = split_meta()

    L = []
    L.append("# E0 — the baseline every later rung is measured against")
    L.append("")
    L.append("*Generated by `make_e0_report.py` from `data/derived/`, the output "
             "of `amog_train.py` — the same engine the whole ladder runs on. "
             "Commit `{}`, {}.*".format(git_commit(),
                                        datetime.now().strftime("%Y-%m-%d")))
    L.append("")

    L.append("## Configuration")
    L.append("")
    L.append("| | |")
    L.append("| :--- | :--- |")
    L.append("| Backbone | {} ({:.1f}M parameters), ImageNet-initialised |".format(
        r.get("backbone"), r.get("n_parameters", 0) / 1e6))
    L.append("| ROI geometry | {} |".format(cm.get("geometry", "unrecorded")))
    L.append("| Split | frozen, {} train / {} val / {} test patients |".format(
        sm.get("n_train", "?"), sm.get("n_val", "?"), sm.get("n_test", "?")))
    L.append("| Split digest | `{}` |".format(str(sm.get("sha256", "?"))[:16] + "…"))
    L.append("| Schedule | {}, {} warm-up epochs, {} epochs, no early stopping |".format(
        r.get("scheduler"), r.get("warmup_epochs"), r.get("epochs_configured")))
    L.append("| Selected epoch | {} (best validation macro-F1 {:.4f}) |".format(
        r.get("selected_epoch"), r.get("selected_val_macro_f1", float("nan"))))
    L.append("| Test predictions | {:,} targets over {} patients |".format(
        r.get("n_samples", 0), sm.get("n_test", "?")))
    L.append("")

    L.append("## Held-out test result")
    L.append("")
    L.append("| Metric | Value |")
    L.append("| :--- | ---: |")
    L.append("| Accuracy | {:.2f}% |".format(r["accuracy"] * 100))
    L.append("| Balanced accuracy | {:.2f}% |".format(
        r.get("balanced_accuracy", float("nan")) * 100))
    L.append("| Macro F1 | {:.4f} |".format(r["macro_f1"]))
    L.append("| **QWK** | **{:.4f}** |".format(r["qwk"]))
    L.append("| ECE (uncalibrated) | {:.4f} |".format(r["ece"]))
    cal = r.get("calibrated") or {}
    if cal:
        L.append("| ECE (temperature-scaled) | {:.4f} |".format(cal.get("ece")))
    L.append("| Severe recall | {:.1f}% |".format(r["severe_recall"] * 100))
    L.append("| Severe graded Normal/Mild | {:.1f}% |".format(
        r["severe_to_normal_rate"] * 100))
    L.append("| Two-grade errors | {:.2f}% |".format(
        r["grade_distance"]["d2_or_more"] * 100))
    L.append("")

    L.append("### Confusion")
    L.append("")
    C = r["confusion_matrix"]
    L.append("| truth \\ predicted | Normal/Mild | Moderate | Severe | recall |")
    L.append("| :--- | ---: | ---: | ---: | ---: |")
    for i, g in enumerate(GRADES):
        n = sum(C[i])
        L.append("| **{}** | {:,} | {:,} | {:,} | {:.1f}% |".format(
            g, C[i][0], C[i][1], C[i][2], C[i][i] / max(n, 1) * 100))
    L.append("")
    L.append("Errors are almost entirely between adjacent grades "
             "({:.2f}% span two), which is the behaviour an ordinal target "
             "should produce. Severe is 6.3% of the corpus and the grade with "
             "the clearest clinical consequence; it is recovered at {:.1f}% "
             "recall, so the score is not an artefact of ignoring the rare "
             "class.".format(r["grade_distance"]["d2_or_more"] * 100,
                             r["severe_recall"] * 100))
    L.append("")

    if cal and r.get("calibration"):
        L.append("### Calibration")
        L.append("")
        L.append("Temperature fitted on the validation split after model "
                 "selection (T = {:.3f}), then applied unchanged to the test "
                 "set: ECE **{:.4f} → {:.4f}**. Both figures are reported, "
                 "because calibration is not guaranteed to help and reporting "
                 "only the corrected column would conceal the cases where it "
                 "does not.".format(r["calibration"]["temperature"],
                                    r["ece"], cal.get("ece")))
        L.append("")

    if ctrl:
        _cn, c = ctrl[0]
        L.append("## Negative control: permuted labels")
        L.append("")
        L.append("Labels were permuted *within* each partition, leaving the "
                 "class distribution untouched and destroying only the "
                 "image-to-label correspondence. A pipeline leaking information "
                 "— through the split, the cache index or the target table — "
                 "would still score well here.")
        L.append("")
        L.append("| Metric | Real | Control |")
        L.append("| :--- | ---: | ---: |")
        L.append("| QWK | {:.4f} | **{:.4f}** |".format(r["qwk"], c["qwk"]))
        L.append("| Macro F1 | {:.4f} | {:.4f} |".format(
            r["macro_f1"], c["macro_f1"]))
        L.append("| Balanced accuracy | {:.2f}% | {:.2f}% |".format(
            r.get("balanced_accuracy", 0) * 100,
            c.get("balanced_accuracy", 0) * 100))
        L.append("| Severe recall | {:.1f}% | {:.1f}% |".format(
            r["severe_recall"] * 100, c["severe_recall"] * 100))
        L.append("")
        verdict = ("collapses to chance, as it must"
                   if abs(c["qwk"]) < 0.05 else
                   "does NOT collapse — investigate before trusting any result")
        L.append("The control {}. Chance balanced accuracy for three classes is "
                 "33.33%. The signal in the real run therefore comes from the "
                 "images, not from the partitioning.".format(verdict))
        L.append("")
    else:
        L.append("## Negative control")
        L.append("")
        L.append("**Not yet run.** Execute:")
        L.append("")
        L.append("```bash")
        L.append("python implementation/amog_train.py --stage E0 --mode real "
                 "--shuffle_labels")
        L.append("```")
        L.append("")

    L.append("## What this result is, and is not")
    L.append("")
    L.append("- It **is** the reference point for E1–E7. Any later rung "
             "claiming a gain must report it against these numbers, on this "
             "split, with this control re-run.")
    L.append("- It **is not** a solution to localisation. The crop is centred "
             "on the released annotation coordinate, so the model is given the "
             "location and asked only to grade it.")
    L.append("- It **is not** comparable to RSNA Kaggle leaderboard scores, "
             "which use a different weighted-log-loss metric on a different "
             "held-out set.")
    L.append("- Accuracy is the least informative column here. The majority "
             "class is 77.3% of the corpus, and a model predicting Normal/Mild "
             "for every target scores that accuracy with QWK exactly 0.0000.")
    L.append("")

    L.append("## Two defects this baseline exposed")
    L.append("")
    L.append("Recorded because they change how any earlier E0 number should be "
             "read, and because both were invisible until two independent "
             "implementations were compared.")
    L.append("")
    L.append("1. **E0 read the wrong sequence for 59.5% of targets.** RSNA "
             "annotates canal stenosis on sagittal T2 and subarticular stenosis "
             "on axial T2, but the model took the sagittal T1 slot "
             "unconditionally. 28,963 of 48,657 targets were graded from a "
             "geometry-projected crop of a sequence no radiologist had marked.")
    L.append("2. **Backbones were randomly initialised.** A 24M-parameter "
             "ResNet-50 was being trained from scratch on 34k crops.")
    L.append("")
    L.append("Together these cost **0.4650 QWK** (0.2553 → 0.7203) and left "
             "Severe recall at 8.3% with 78.4% of severe cases graded "
             "Normal/Mild.")
    L.append("")

    L.append("## Reproducing")
    L.append("")
    L.append("```bash")
    L.append("python implementation/05_roi_crops/build_roi_cache.py \\")
    L.append("    --rsna_dir <RSNA> --name rsna_roi_v2 --fov_mm 60 --radius 1")
    L.append("python implementation/amog_train.py --stage E0 --mode real "
             "--backbone resnet50")
    L.append("python implementation/amog_train.py --stage E0 --mode real "
             "--backbone resnet50 --shuffle_labels")
    L.append("python implementation/99_audit/make_e0_report.py")
    L.append("```")
    L.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L) + "\n")
    print("wrote {}".format(OUT))
    print("real runs: {}   control runs: {}".format(len(real), len(ctrl)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
