#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Run the component test suite and render its result for Chapter 4.

The suite in test_components.py states a Chapter 3 property per test and tries
to falsify it. This script executes it and records the outcome, so Chapter 4 can
cite verification evidence rather than assert that the code is correct.

    python implementation/99_audit/make_verification_report.py
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from datetime import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
IMPL = os.path.dirname(HERE)
ROOT = os.path.dirname(IMPL)
OUT = os.path.join(ROOT, "thesis", "chapter4", "component_verification.md")

SECTION_RE = re.compile(r"^(\d+)\.\s+(.*)$")
RESULT_RE = re.compile(r"^\s*\[(PASS|FAIL)\]\s+(.*)$")


def git_commit():
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
            stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return "unknown"


def main() -> int:
    proc = subprocess.run(
        [sys.executable, os.path.join(HERE, "test_components.py")],
        cwd=ROOT, capture_output=True, text=True)
    raw = proc.stdout

    sections, current = [], None
    for line in raw.splitlines():
        m = SECTION_RE.match(line.strip())
        if m:
            current = {"title": m.group(2).strip(), "tests": []}
            sections.append(current)
            continue
        r = RESULT_RE.match(line)
        if r and current is not None:
            current["tests"].append((r.group(1), r.group(2).strip()))

    n_pass = sum(1 for s in sections for st, _ in s["tests"] if st == "PASS")
    n_fail = sum(1 for s in sections for st, _ in s["tests"] if st == "FAIL")

    L = []
    L.append("# Component Verification against Chapter 3")
    L.append("")
    L.append("*Generated by `make_verification_report.py`, which executes "
             "`implementation/99_audit/test_components.py` and records what it "
             "returned. Run at commit `{}` on {}.*"
             .format(git_commit(), datetime.now().strftime("%Y-%m-%d %H:%M")))
    L.append("")
    L.append("## What this is")
    L.append("")
    L.append("Each test states a property Chapter 3 requires and then tries to "
             "falsify it on constructed inputs whose correct answer is known "
             "independently of the implementation. They are not smoke tests: a "
             "test that only checks the code runs would have passed on the "
             "fabricated implementation this project replaced.")
    L.append("")
    L.append("Two categories of defect that motivated this approach, both of "
             "which were invisible to reading the source:")
    L.append("")
    L.append("- A checkpoint was loaded, asserted non-empty, and never applied. "
             "The assertion read like a restore and only verified that the file "
             "parsed, so the held-out test ran on final-epoch weights.")
    L.append("- The E4 rung constructed a projection head that no forward path "
             "referenced. Only a gradient probe showed that all four of its "
             "tensors received no gradient.")
    L.append("")
    L.append("**Result: {} passed, {} failed.**".format(n_pass, n_fail))
    L.append("")

    L.append("## By area")
    L.append("")
    L.append("| Area | Passed | Failed |")
    L.append("| :--- | ---: | ---: |")
    for s in sections:
        p = sum(1 for st, _ in s["tests"] if st == "PASS")
        f = sum(1 for st, _ in s["tests"] if st == "FAIL")
        L.append("| {} | {} | {} |".format(s["title"], p, f))
    L.append("")

    if n_fail:
        L.append("## Open findings")
        L.append("")
        L.append("These are recorded rather than hidden. A failing test here is "
                 "a known deviation from Chapter 3 with a decision attached, not "
                 "an unexplained defect.")
        L.append("")
        for s in sections:
            fails = [t for st, t in s["tests"] if st == "FAIL"]
            if fails:
                L.append("**{}**".format(s["title"]))
                L.append("")
                for t in fails:
                    L.append("- {}".format(t))
                L.append("")

    L.append("## Full results")
    L.append("")
    for s in sections:
        L.append("### {}".format(s["title"]))
        L.append("")
        for st, t in s["tests"]:
            L.append("- {} {}".format("PASS" if st == "PASS" else "**FAIL**", t))
        L.append("")

    L.append("## Reproducing")
    L.append("")
    L.append("```bash")
    L.append("python implementation/99_audit/test_components.py")
    L.append("python implementation/99_audit/make_verification_report.py")
    L.append("```")
    L.append("")
    L.append("The suite exits non-zero while any finding remains open, so it can "
             "gate a campaign rather than merely inform one.")
    L.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L) + "\n")
    print("wrote {}".format(OUT))
    print("{} passed, {} failed across {} areas".format(n_pass, n_fail, len(sections)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
